FROM python:3.11 AS builder
WORKDIR /build

COPY requirements.txt .
RUN pip install --no-cache-dir --target=/build/deps -r requirements.txt

COPY generate_random_dataset.py train_model.py .
ENV PYTHONPATH=/build/deps
RUN python generate_random_dataset.py && python train_model.py

# minmimal runtime
FROM python:3.11-slim
WORKDIR /app

COPY --from=builder /build/deps /usr/local/lib/python3.11/site-packages
COPY --from=builder /build/model.joblib .
COPY app.py .

EXPOSE 8000
CMD ["python", "-m", "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
